#!/usr/bin/env bash
#check for command line arguments

if [ $# -lt 4 ]
then 
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

#assign paramentals to variables

file_path=$1
ip=$2
username=$3
path_to_ssh_key=$4

# disabling strict host key checking

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$file_path" "$username@$ip:~/"


# Checking if file transfer was susccessful
if [ $? -eq 0 ]
then 
	echo "File was transfared successfully"
else
	echo "File transfare not successful"
fi

