#!/usr/bin/env bash
# config web-01 to have HTTP Response header

#update packages
sudo apt-get update
sudo apt-get install -y nginx

#create index page
echo "Hello World!" | sudo tee /var/www/html/index.html

#redirection performance
string_for_replacement="server_name_;\n\trewrite ^\/redirect_me https:\/\/github.com\/z-bot-pi permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#custom error page creation

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

#CUSTOM http Response header

sudo sed -i "server_name _;/a add_header X-Serverd-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#Test for syntax errors
sudo nginx -t

#restart nginx
sudo service nginx restart


