#!/usr/bin/env bash
#Configures an Ngix server to listen on port 80

#remove default Nginx configuration file
rm /etc/nginx/sites-enabled/default
#Configure Nginx to listen on port 80 for all active IPv4 IPs
ln -a /etc/nginx/sites-available/default /wtc/nginx/sites-enabled/default
#restart Nginx
service nginx restart 
